### ISSUE TITLE
coin.account-create cookbook example doesn't work

### ISSUE THREAD

**Issue by ColinGilbert** [kadena-community/docs#103]
Hi,

I tried running the coin.account-create example [here](https://docs.kadena.io/build/frontend/pact-lang-api-cookbook#create-account) from the cookbook examples, and every time I got the error message:

Attempt to buy gas failed with: : Failure: Tx Failed: read: row not found: <gas buyer's public key>

Could you check to see if this example works for you and update it if it doesn't?

Thanks!

**Comment by trendzetter** [comment]
It means your account specified as gas buyer doesn't exist on the chain where you tried to execute the transaction.

For more interactive support you probably want to ask on Discord: https://discord.gg/kadena

**Comment by ColinGilbert** [comment]
I can confirm that the gas buyer's account exists on the specific chain, as I can perform transfers and transfer-creates.

**Comment by ColinGilbert** [comment]
I solved it - my account was using a fancy name and once I switched the meta.sender from the pubkey to its name, it worked. :)
