### ISSUE TITLE
Description incomplete on the Whitepapers -> Kuro page

### ISSUE THREAD

**Issue by r0nnybums** [kadena-community/docs#2]
https://docs.kadena.io/basics/whitepapers/kuro-layer-2

"Lightning+BTC powers El Salvador, but Chainweb's layer 1 scalabl" 

If you want me to just make something up and submit a PR then let me know 👍

**Comment by r0nnybums** [comment]
Seems like it's the same on the Chainweb and Pact whitepaper pages as well.

**Comment by bertrandkda** [comment]
Good spot r0nnybums! We will address it asap, also keen to see what you would suggest in a PR. Thanks!
